
DROP DATABASE IF EXISTS IAD;

CREATE DATABASE IF NOT EXISTS IAD;
use IAD;


CREATE TABLE IF NOT EXISTS lightControl (
`ID` int NOT NULL AUTO_INCREMENT PRIMARY KEY, 
`dateTime` DATETIME,
`ledOutput` SMALLINT,
`sensorReading` SMALLINT
);
